package shared;

public enum MessageType {
    LOGIN, CLIENT_CALL, NODE_CALL, NAME_LOCK_REQ, NAME_LOCK_REPLY, NAME_LOCK_ANNOUNCE, NAME_LOCK_RELEASE, CLIENT_TRANSFER_REQ, DISCONNECT, TRANSFER, CLIENT_ARRIVAL, N_RIP

}
